spring:
  application:
    name: claims-loss-assessment
  datasource:
    password: root
    username: root
    url: jdbc:mysql://47.100.79.206:3306/claims?characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  cloud:
    nacos:
      discovery:
        server-addr: 47.100.79.206:8848
server:
  port: 11000
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.dm.claims.entity